name: API Tests

on:
  push:
  pull_request:

jobs:
  api-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman & HTML reporter
        run: npm install -g newman newman-reporter-html

      - name: Run API Tests
        run: >
          newman run My_Collection.postman_collection.json
          -e environment.json
          -r cli,html
          --reporter-html-export report.html

      - name: Upload HTML Report
        if: always()  # upload even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: api-test-report
          path: report.html